### ISSUE TITLE
bug in parser

### ISSUE THREAD

**Issue by 14corman** [14corman/AIDescisionTree#14]
I am not sure if you said if the parser was done yet or not. It was showing that the list of labels (y) that were being returned was a string. However, to work with the graph this has to be an int list. I tried to add int_of_string to the label when it is added to the list, but this is throwing an error now. Need to finalize parser before we can continue.

**Comment by the5thbeatle** [comment]
I know the problem! I forgot to map the classes to numbers, so it was returning a list of strings. I'll fix that and push immediately.

**Comment by 14corman** [comment]
Ok. I did not know that you were already aware. Sorry about that. That would explain why it could not convert the classes to int then. You can take your time if you have other things to work on. I am doing other homework right now.

**Comment by the5thbeatle** [comment]
I actually didn't realize it until you mentioned it, but I knew when you posted it what I had missed.

**Comment by the5thbeatle** [comment]
I've pushed a fix.
