### ISSUE TITLE
Pick the 4 datasets.

### ISSUE THREAD

**Issue by 14corman** [14corman/AIDescisionTree#2]
Need to pick 4 datasets from [http://archive.ics.uci.edu/ml/datasets.php](http://archive.ics.uci.edu/ml/datasets.php) that have the following qualities:

1. multivariate (more than 1 class)
2. classification (no regression datasets)
3. “Categorical” attribute type (all inputs need to be discrete)
4.  100 or more examples

**Comment by 14corman** [comment]
Jace:

> Here are links to 2 datasets that I thought could be interesting.  
http://archive.ics.uci.edu/ml/datasets/Chess+%28King-Rook+vs.+King%29
http://archive.ics.uci.edu/ml/datasets/Breast+Cancer

Noah:

> Here are the datasets I found:
Predicting how normal a heart is based on 22 binary features from a cardiac SPECT:
http://archive.ics.uci.edu/ml/datasets/SPECT+Heart
This one attempts to determine whether a US Representative was Democrat or Republican based on how they voted on certain bills (contains missing data):
http://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/

**Comment by 14corman** [comment]
So at a glance it looks like we will need to create new variables for the chess dataset based on what variables are given. Do we have to predict how many moves it will take to take the opposing king in that dataset? I am not sure what the moves to take is since there is a 0 in there.

For the voting dataset, here is the correct URL to use I think: 
[http://archive.ics.uci.edu/ml/datasets/congressional+voting+records](http://archive.ics.uci.edu/ml/datasets/congressional+voting+records)

The other link went to an apache look into a file directory.

**Comment by the5thbeatle** [comment]
Yes, thank you. I grabbed the wrong tab.

Noah

**Comment by Neuby121** [comment]
A 0 value for depth-of-win represents that there's currently a checkmate.  No additional moves are necessary to win the game.
