### ISSUE TITLE
Create classifier file

### ISSUE THREAD

**Issue by 14corman** [14corman/AIDescisionTree#5]
Create a code file to take the dot file and run it through the parser to make the graph, take the csv and run it through the parser to get examples, and run the 2 together to get classifications.

Both parsers should be made, and the tree code should be there as well so this should not be too difficult.

**Comment by the5thbeatle** [comment]
I started to finish the preprocessing so that the datasets match the test format, and it looks like this issue might have a difficult solution.

**Comment by 14corman** [comment]
I have already finished the classifier side. I have updated the test file as well to show how classifying will happen. I need to add comments and will post the updated code in a while when I have time. 

@the5thbeatle was that last comment supposed to go into the preprocessing issue?

**Comment by the5thbeatle** [comment]
My last comment was only half done. I clicked cancel and then accidentally
clicked “cancel and close” as well (I reopened it immediately). It’s now
irrelevant.

**Comment by 14corman** [comment]
Created, finalized (I think), and added comments to the classifier file. It is added in the newest push.
